system:
  env: debug # debug | test | release
  host: 127.0.0.1
  port: 8888
  dbType: mysql
  ossType: local
  useMultipoint: false
  useRedis: false
  ipLimitCount: 15000
  ipLimitTime: 3600
  routerPrefix: "_sys"
  frontRouterPrefix: "_/"
jwt:
  signingKey: 273628f7-9fb4-4e73-8f8d-ca954710d01d
  expiresTime: 7d
  bufferTime: 1d
  issuer: qmPlus
local:
  path: uploads/file
  storePath: uploads/file

# 数据库
db:
  default:
    driver: mysql
    path:
    port:
    config: charset=utf8mb4&parseTime=True&loc=Local
    dbname:
    username:
    password:
    prefix:
    singular: false
    engine: ""
    maxIdleConns: 10
    maxOpenConns: 20
    logMode: error
    logZap: false
  another:
    driver: mssql
    path:
    port:
    config: charset=utf8mb4&parseTime=True&loc=Local
    dbname:
    username:
    password:
    prefix:
    singular: false
    engine:
    maxIdleConns: 10
    maxOpenConns: 20
    logMode: error
    logZap: false
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
captcha:
  keyLong: 1
  imgWidth: 240
  imgHeight: 80
  openCaptcha: 0
  openCaptchaTimeout: 3600
zap:
  level: info
  prefix: ''
  format: console
  director: log
  encodeLevel: LowercaseColorLevelEncoder
  stacktraceKey: stacktrace
  maxAge: 0
  showLine: true
  logInConsole: true
cors:
  mode: strict-whitelist
  whitelist:
    - allowOrigin: example1.com
      allowMethods: POST, GET
      allowHeaders: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
      exposeHeaders: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,Content-Type
      allowCredentials: true
    - allowOrigin: example2.com
      allowMethods: GET, POST
      allowHeaders: content-type
      exposeHeaders: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,Content-Type
      allowCredentials: true